const dna = {
  personality: { keywords: ['Editorial', 'Expressive'], description: 'Dense editorial energy comes from exaggerated type scale and rough accent marks.' },
  composition: { style: 'asymmetric', alignment: ['Headline anchors the left edge; small metadata balances the opposite corners.'], edgeUsage: 'high', description: 'Distributed corner information counterbalances a dominant offset headline; the eye crosses the canvas diagonally.' },
  density: { level: 'high', whitespaceStrategy: 'Small breathing spaces separate groups; broad isolated empty regions are deliberately absent.', description: 'Large typography and peripheral metadata keep nearly the whole canvas visually active.' },
  typography: { headlineScale: 'oversized', hierarchy: 'Heavy compressed headlines dominate tiny, light peripheral metadata.', behavior: ['Tight line spacing and abrupt line breaks make the headline act as a graphic mass.'], description: 'Bold sans-serif typography forms the main graphical element rather than a label above a picture.' },
  color: { strategy: 'A pale ground supports near-black type and one saturated orange accent.', contrastStrategy: 'Dark headline on a pale ground creates the strongest readable contrast; orange marks remain secondary.', accentUsage: 'Orange is concentrated in imperfect emphasis marks near important words.', description: 'Three palette roles separate reading content from expressive decoration.' },
  imagery: { role: 'Photography is optional across the family rather than a universal requirement.', treatment: 'When present, an off-center crop supports the headline without obscuring its letters.', description: 'One slide uses photography while another relies entirely on typography.' },
  decorativeLanguage: { elements: ['Rough circles', 'Hand-drawn arrows'], behavior: 'Orange irregular strokes guide attention toward important headline words.', description: 'Imperfect marks soften the strict alignment; flat layers have no visible drop shadows.' },
  visualHierarchy: ['First: the headline through overwhelming size and dark contrast.', 'Second: orange emphasis marks through saturation and proximity to key words.', 'Third: peripheral metadata through its corner placement and much smaller scale.'],
  distinctiveCharacteristics: ['Oversized type and tiny corner labels produce extreme scale contrast.', 'Rough orange circles interrupt an otherwise controlled alignment.', 'Limited empty regions keep the canvas active all the way to its edges.'],
  rules: ['Keep perceived occupancy high with content distributed across the canvas.', 'Make the headline the largest graphical mass in the composition.', 'Use tiny corner metadata to counterbalance the oversized headline.', 'Reserve saturated orange for irregular emphasis marks near important words.', 'Maintain dark readable typography over the pale background.'],
  antiRules: ['Do not reduce the headline into a small centered label.', 'Do not replace distributed content with a generic centered card and broad margins.', 'Do not remove the irregular accent marks or convert everything to monochrome.'],
  uncertainties: ['The exact font family cannot be reliably identified from the reference alone.'],
}
const refs = [1, 2].map(i => ({ id: `ref-${i}`, url: `/design-references/ref-${i}.jpg`, name: `Reference ${i}`, width: 1080, height: 1350 }))
const reference = id => ({ referenceId: id, dna: structuredClone(dna), evidence: dna.distinctiveCharacteristics.map((principle, i) => ({ principle, observation: dna.visualHierarchy[i] })) })
const family = ids => ({ name: 'Dense Expressive Editorial', dna: structuredClone(dna), sharedCharacteristics: dna.distinctiveCharacteristics.map(characteristic => ({ characteristic, referenceIds: ids })), differences: ['Reference ref-1 uses a large crop; reference ref-2 contains no photography. This is a slide-specific choice.'] })
const study = () => ({ schemaVersion: 1, name: family([]).name, referenceImages: refs, designDNA: structuredClone(dna), referenceStudies: refs.map(r => reference(r.id)), sharedCharacteristics: family(refs.map(r => r.id)).sharedCharacteristics, differences: family([]).differences })
module.exports = { dna, refs, reference, family, study }
