/** Asset instructions derive from the copy and already planned frame; no text-model call. */
export function localAssetBrief(layout:any,slide:any,idea:any) {
 if(!layout.needs_visual)return {slot_id:layout.slot_id,slot_label:layout.slot_id,needs_visual:false,preferred_source:'none',generation_prompt:'',search_queries:[],search_keywords:[],source_reason:'Text-led composition: preserve the reading area instead of adding a competing image.'}
 const text=[slide.headline||slide.title,slide.body||slide.supportingText].filter(Boolean).join('. ')
 // Match the current slide before the campaign topic, which otherwise makes every scene identical.
 const scenes:[RegExp,string[],string][]=[
  [/costur|tecido|roupa|vestu[aá]rio|garment|apparel|fabric|seam|sportswear/i,['Object-only: a complete unbranded athletic garment arranged to reveal flexible seams, articulated panels and stretch fabric, no people','Object-only: two overlapping stretch-fabric swatches with clearly visible flexible stitching and gently curved folds, no people'],'stretch fabric garment seams'],
  [/agricult|farming|wheat|trigo|colheita|harvest|cultiv|planta[çc][ãa]o/i,['Object-only: a complete bundle of ripe wheat stalks with visible seed heads, no people','Environment-only: cultivated crop rows in a sunlit field, no people','Object-only: a young seedling with its complete root ball and a small mound of soil, no people'],'wheat farming field'],
  [/corrida|correr|running|marathon|maratona|sprint/i,['a runner in mid-stride demonstrating natural running form, complete head, arms and shoes visible','a runner moving along an outdoor track, showing the full running action'],'runner running track'],
  [/tabag|fum(ar|o|ante)|smok(ing|er)|cigar|nicotin/i,['Object-only: one complete unbranded cigarette with a small wisp of smoke, no people','Object-only: a broken unbranded cigarette beside loose tobacco, no people'],'cigarette tobacco'],
  [/energia solar|solar|renewable|renov[aá]vel/i,['Environment-only: a solar panel array catching daylight, no people','Object-only: a complete compact solar panel and battery, no people'],'solar panels energy'],
  [/poupan|savings|or[çc]amento|budget|finan/i,['Object-only: a small stack of coins beside a calculator and notebook, no people','Object-only: a transparent savings jar containing coins, no people'],'savings coins calculator'],
  [/educa|learning|estudo|study|livro|book/i,['Object-only: an open book beside a pencil and compact stack of books, no people','Environment-only: a quiet library reading area with bookshelves, no people'],'books learning library'],
  [/\bbim\b|erros? de projeto|modela[çc][ãa]o|clash|blueprint/i,['Object-only: a compact architectural scale model with visibly separated structural layers beside one neatly rolled blueprint, no people','Object-only: an unrolled architectural blueprint with a drafting compass and triangular ruler, all paper edges and tools fully visible, no people','Object-only: two small structural building models side by side, one with misaligned beams and one precisely aligned, no people'],'architectural model blueprint'],
  [/fissur|rachadur|parede|wall|renova|obra|constru/i,['building renovation site with detailed wall surfaces and construction materials'],'building renovation wall'],
  [/arquitet|architecture|interior/i,['architectural building facade with visible structural details','interior space with natural light and architectural details'],'architecture building interior'],
  [/paisagem|landscape/i,['wide scenic landscape with natural light and an open horizon'],'scenic landscape'],
  [/regist|register|conta|sign.?up/i,['entrepreneur seated at a desk entering account details on a desktop keyboard, monitor viewed from behind','business founder using a smartphone to complete account registration','Object-only: a complete smartphone and notebook for account registration, no people'],'account registration'],
  [/cat[aá]logo|catalog|carregue|upload|produtos/i,['product photographer arranging merchandise beside a camera on a tripod','overhead arrangement of neatly organized products, camera and inventory notebook','shop owner photographing a product with a smartphone'],'product photography'],
  [/pagament|checkout|payment/i,['customer tapping a bank card on a payment terminal held by a merchant','close-up of a complete contactless payment terminal and bank card'],'contactless payment'],
  [/entrega|delivery|courier/i,['courier handing a parcel to a customer at a doorway','Object-only: a compact delivery van and parcel arrangement, no people'],'parcel delivery'],
  [/armaz|estoque|stock|fulfil|logistic|warehouse|shipping/i,['warehouse operator scanning a parcel barcode with a handheld scanner','organized parcels on a warehouse conveyor with a barcode scanner','warehouse worker checking shelves with a clipboard'],'warehouse inventory'],
  [/cozinh|chef|cook|food/i,['chef stirring a pan with fresh ingredients beside the stove','Object-only: fresh ingredients arranged beside a complete cooking pot and wooden spoon, no people'],'chef cooking'],
  [/loja|vend|store|ecommerce|shop/i,['confident shop owner presenting their merchandise with an expressive welcoming gesture','entrepreneur celebrating a new sale while looking at a smartphone','carefully arranged retail products with shopping bags'],'small business retail'],
  [/trabalh|work|computer|digital/i,['professional typing at a desktop workstation in three-quarter view','colleagues discussing a document at a work table'],'office working']
 ]
 const headline=slide.headline||slide.title||''
 const match=scenes.find(([pattern])=>pattern.test(headline))||scenes.find(([pattern])=>pattern.test(text))||scenes.find(([pattern])=>pattern.test(String(idea.topic||'')))
 const seed=[idea.id,layout.slot_id,text].join('|').split('').reduce((n,c)=>(Math.imul(n,31)+c.charCodeAt(0))>>>0,0)
 const isolated=layout.treatment==='isolated_subject'||!layout.background&&layout.treatment!=='environmental'
 const options=match?.[1].filter(scene=>!isolated||!scene.startsWith('Environment-only:'))||[]
 let subject=options.length?options[seed%options.length]:'Choose one concrete visual subject that directly explains this slide: '+String(headline||idea.topic||text).slice(0,250)+'. Prefer the actual object, material, organism or place being discussed. Show a person only when their action or emotion is essential to the message; never default to a business portrait or laptop user.'
 if(isolated&&!/Object-only:/i.test(subject)){
  const objects:[RegExp,string[]][]=[
   [/fissur|rachadur|parede|wall|renova|obra|constru/i,['a complete claw hammer beside a compact stack of three bricks','a complete trowel beside a small freestanding wall cross-section','a rolled blueprint with a hard hat and tape measure']],
   [/arquitet|architecture|interior/i,['a small architectural scale model with a drafting ruler','a complete rolled floor plan with a compass']],
   [/\bdados\b|\bdata\b|\bm[eé]tricas?\b|\bkpis?\b|\bestat[ií]stic|\banalytics\b/i,['a compact set of physical bar-chart blocks and a magnifying glass','a complete notebook with abstract unlabeled charts and a pencil']],
   [/armaz|estoque|stock|fulfil|logistic|warehouse|shipping/i,['a handheld barcode scanner beside three neatly stacked parcels','a compact warehouse shelf model containing parcels']],
   [/trabalh|work|computer|digital/i,['a complete standalone monitor and keyboard, no desk','a notebook, pencil and desk clock arranged as a compact still life']]
  ]
  const object=objects.find(([pattern])=>pattern.test(headline))||objects.find(([pattern])=>pattern.test(text))
  if(object)subject='Object-only: '+object[1][seed%object[1].length]+', no people, no hands, no table or workbench'
 }
 const query=match?.[2]||String(headline||idea.topic||'').slice(0,160)
 return {slot_id:layout.slot_id,slot_label:layout.slot_id,needs_visual:true,subject_description:subject,visual_purpose:text.slice(0,700),generation_prompt:'Create a premium commercial visual in the requested image style for this exact slide: '+text.slice(0,1200)+'. Brand campaign context (secondary to the slide): '+String(idea.topic||'').slice(0,200)+'. Visible scene: '+subject+'. SUBJECT SELECTION: The slide meaning determines whether to show an object, plant, animal, landscape, interior or person. A person is appropriate for a human action or emotion (running, caregiving, collaboration), not as a generic representative of an industry. Use the named object itself for object-led topics. Do not turn generic words such as strategic, growth, performance or improvement into financial charts, magnifying glasses or business symbols. Charts are appropriate only when quantitative data is the actual subject. Do not insert people into object-only or environment-only scenes. Preserve the chosen category even if brand references show people. Show the specific activity clearly with believable tools and materials. Use natural skin and fabric textures, anatomically correct hands, physically plausible objects, restrained studio lighting and an editorial camera viewpoint. For a cutout, the entire subject assembly must occupy at most 80 percent of the image width with 10 percent clear margin on each side. Include both ends of tables, desks, chairs and all props. Image scale within the slide will be handled during layout. Keep the entire head and all essential props visible. Frame the subject and props completely on both horizontal sides by default. Never crop both the left and right sides. For isolated subjects neither horizontal side may reach the image boundary: complete both outer contours with clear margin. Use a wider camera view or rearrange props rather than cutting off both ends of a table, vehicle or equipment. Match the planned frame aspect ratio. Do not default to a smiling person holding a laptop or sealing a box; only show those actions when explicitly required by this scene. No invented lettering, watermarks, duplicated limbs, floating graphics or collage. '+layout.brief,search_queries:[query,query.split(' ').slice(0,2).join(' ')],search_keywords:query.split(/\s+/),preferred_source:layout.background?'unsplash':'ai_generated',source_reason:'Specific slide action and varied scene, chosen for the planned frame'}
}
