import Link from 'next/link'
import { ArrowRight, ArrowUpRight, Check, Plus, X } from 'lucide-react'
import LandingHeader from './LandingHeader'
import HeroArt from './HeroArt'
import BrandDemo from './BrandDemo'
import CustomCursor from './CustomCursor'
import ScrollReveal from './ScrollReveal'
import SmoothScroll from './SmoothScroll'
import {
  BatkleLogo,
  Card,
  CardTitle,
  Container,
  Eyebrow,
  HangingBat,
  Section,
  SectionTitle,
  arrowClass,
  buttonClass,
  cn,
  displayClass,
  liftClass,
  reveal,
} from './brand'

const START_HREF = '/app'

// One avatar per sample brand in the demo, plus one more.
const BRAND_AVATARS = [
  { letter: 'F', className: 'bg-[#F2A900] text-bk-ink' },
  { letter: 'N', className: 'bg-[#3B5BFF] text-white' },
  { letter: 'C', className: 'bg-[#1F7A5A] text-white' },
  { letter: 'S', className: 'bg-[#E4572E] text-bk-ink' },
  { letter: 'K', className: 'bg-bk-ink text-bk-butter dark:bg-bk-chip' },
]

const INDUSTRIES = ['Construction', 'Fintech', 'Local services', 'Agencies', 'Creative studios']

const STEPS = [
  {
    title: 'Add your brand',
    body: 'Paste your website URL. Batkle researches it and builds a brand profile: services, projects, differentiators, audience, tone of voice, language, colors, fonts and logo. All of it stays editable.',
  },
  {
    title: 'Pick your designs',
    body: 'Choose visual styles from the Design Library. Each one was learned from a few real reference posts. It is a visual language, not a fixed template, so every post varies while keeping one look.',
  },
  {
    title: 'Get ideas',
    body: "Batkle suggests post ideas that rotate across your services, projects and strengths, always in your brand's language and never repeating the same subject.",
  },
  {
    title: 'Generate a post',
    body: 'One click produces the headline, slides, caption, hashtags and the design, as a single post or a carousel (1080×1350). Images are generated by AI or picked from stock and your own gallery.',
  },
  {
    title: 'Edit and export',
    body: 'Every text, shape, image and logo stays editable in the canvas editor. Tweak it, export it as images and publish.',
  },
]

const AUDIENCES = [
  {
    title: 'Small businesses',
    body: 'Stay visible on Instagram without hiring a designer. Batkle already knows your services and your projects.',
  },
  {
    title: 'Agencies',
    body: 'Give every client their own workspace, brand profile and look, and keep each one consistent from post to post.',
  },
  {
    title: 'Marketers',
    body: 'Go from idea to a finished carousel in one click and keep your time for strategy.',
  },
]

const WITHOUT = [
  'Brief a designer for every post',
  'Write every caption from scratch',
  'Watch the brand look drift from post to post',
  'Go quiet when the week gets busy',
]
const WITH = ['Paste your website once', 'Pick the designs you like', 'Generate on-brand posts in one click', 'Edit anything, then export']

// Placeholders from the design: replace with real customer quotes and plans before launch.
const QUOTES = [
  '[CUSTOMER QUOTE: one or two sentences about how Batkle changed their posting routine.]',
  '[CUSTOMER QUOTE: a second quote, ideally about staying on brand or saving time.]',
]
const PLANS = [{ popular: false }, { popular: true }, { popular: false }]

const FAQS = [
  {
    q: 'How does Batkle learn my brand?',
    a: 'Paste your website URL. Batkle researches it and builds a brand profile with your services, projects, audience, tone of voice, language, colors, fonts and logo. You can edit every part of it.',
  },
  {
    q: 'Can I edit the posts it creates?',
    a: 'Yes. Every text, shape, image and logo stays editable in the canvas editor. The AI drafts, you decide.',
  },
  {
    q: 'Which languages does it write in?',
    a: "Your brand's language, picked up from your website. A business in Lisbon gets European Portuguese, not a translation. You can change it in the brand profile.",
  },
  {
    q: 'Does every post look the same?',
    a: 'No. Each design in the Design Library is a visual language learned from real posts, not a fixed template, so every post varies while keeping one recognizable look.',
  },
  {
    q: 'Can I use my own photos?',
    a: "Yes. Upload them to your brand's gallery and use them alongside stock photos and AI-generated images and cutouts.",
  },
  {
    q: 'How much does it cost?',
    a: '[ADD YOUR PRICING ANSWER.] See the plans above for what each one includes.',
  },
]

const FOOTER_LINKS = [
  {
    title: 'Product',
    links: [
      ['How it works', '#how-it-works'],
      ['Features', '#features'],
      ['Pricing', '#pricing'],
      ['FAQ', '#faq'],
    ],
  },
  {
    title: 'Company',
    links: [
      ['Contact', '#'],
      ['Privacy', '#'],
      ['Terms', '#'],
    ],
  },
]

// The hero panel colour. The avatar rings use it too, so they read as cut-outs.
const heroPanel = 'bg-[#EFEEE9] dark:bg-bk-alt'
const heroRing = 'ring-[#EFEEE9] dark:ring-bk-alt'

function WebsiteForm() {
  // A plain GET form, so it works before hydration: /app?website=...
  return (
    <form
      action={START_HREF}
      method="get"
      className="mx-auto mt-[clamp(10px,2.2svh,32px)] flex w-full max-w-[560px] items-center gap-2 rounded-xl border-2 border-bk-fg bg-bk-surface p-1.5 pl-4 transition-shadow focus-within:shadow-[0_0_0_4px_rgb(255_216_77/0.55)] motion-safe:animate-bk-enter sm:p-2 sm:pl-5"
      style={{ animationDelay: '280ms' }}
    >
      <label htmlFor="bk-hero-website" className="sr-only">
        Your website
      </label>
      <input
        id="bk-hero-website"
        name="website"
        type="text"
        inputMode="url"
        autoComplete="url"
        spellCheck={false}
        placeholder="yourwebsite.com"
        className="h-[clamp(40px,5.4svh,52px)] min-w-0 flex-1 bg-transparent text-[16px] text-bk-fg outline-none placeholder:text-bk-muted/80 sm:text-[18px]"
      />
      <button
        type="submit"
        className="h-[clamp(40px,5.4svh,52px)] shrink-0 rounded-lg bg-bk-ink px-3.5 text-[15px] min-[380px]:px-4 min-[380px]:text-[16px] font-bold text-bk-butter transition-[background-color,transform] duration-200 hover:bg-black active:scale-[0.97] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-bk-fg dark:bg-bk-butter dark:text-bk-ink dark:hover:bg-[#FFCD24] sm:px-6 sm:text-[17px]"
      >
        Add your brand
      </button>
    </form>
  )
}

function Thumb({ kind }) {
  if (kind === 'palette') {
    return (
      <span className="grid size-[clamp(36px,6svh,52px)] shrink-0 grid-cols-2 overflow-hidden rounded-[4px] ring-1 ring-bk-ink/10">
        <span className="bg-bk-ink" />
        <span className="bg-[#F2A900]" />
        <span className="bg-[#F5F1E8]" />
        <span className="bg-[#3B5BFF]" />
      </span>
    )
  }
  const dark = kind === 'story'
  return (
    <span
      className={cn(
        'flex h-[clamp(44px,7.4svh,64px)] w-[clamp(36px,6svh,52px)] shrink-0 flex-col justify-center overflow-hidden rounded-[3px] p-[4px] font-bk-display text-[7px] font-bold leading-[1.05] tracking-[-0.02em] ring-1 sm:text-[8px]',
        dark ? 'justify-end bg-bk-ink text-bk-butter ring-white/10' : 'bg-bk-butter text-bk-ink ring-bk-ink/10',
      )}
      lang="pt-PT"
    >
      {dark ? 'A nossa história.' : 'Menos tarefas, mais tempo.'}
    </span>
  )
}

const HERO_CARDS = [
  { label: 'Brand profile', title: 'Learns your brand from your URL', href: '#how-it-works', thumb: 'palette' },
  { label: 'Content ideas', title: 'Ideas that rotate, never repeat', href: '#features', thumb: 'idea' },
  { label: 'Posts and carousels', title: 'Designed in your look, editable', href: '#demo', thumb: 'story' },
]

/**
 * The hero is exactly one screen: the panel fills the viewport below the sticky header (65 px, 73 px from sm) and
 * its type, spacing and cards scale with the screen height, so nothing falls below the fold. The illustration takes
 * whatever height is left, with the cards resting on its lower edge. Very short screens let the panel grow instead.
 */
function Hero() {
  return (
    <section className="bg-bk-bg px-3 py-3 sm:px-5 sm:py-5">
      <div
        className={cn(
          'mx-auto flex min-h-[calc(100svh-89px)] max-w-[1600px] flex-col overflow-hidden rounded-[24px] border border-bk-line sm:min-h-[min(calc(100svh-113px),1100px)]',
          heroPanel,
        )}
      >
        <div className="px-5 pt-[clamp(16px,3.6svh,96px)] text-center sm:px-8">
          <h1
            className="mx-auto max-w-[9.2em] font-bk-display text-[length:clamp(28px,min(9.4vw,5.4svh),104px)] font-bold leading-[0.98] tracking-[-0.025em] motion-safe:animate-bk-enter sm:text-[length:clamp(36px,min(7.3vw,7.4svh),104px)]"
          >
            Paste your website. <br className="hidden sm:inline" />
            Get{' '}
            <span className="relative isolate whitespace-nowrap dark:text-bk-ink">
              <span
                aria-hidden="true"
                className="absolute -inset-x-[0.04em] bottom-[-0.06em] top-[0.79em] -z-10 bg-bk-butter dark:top-[0.1em]"
              />
              on-brand
            </span>{' '}
            <br className="hidden sm:inline" />
            Instagram posts.
          </h1>

          <div
            className="mt-[clamp(8px,1.6svh,28px)] flex flex-wrap items-center justify-center gap-x-3 gap-y-1 motion-safe:animate-bk-enter"
            style={{ animationDelay: '70ms' }}
          >
            <span className="flex" aria-hidden="true">
              {BRAND_AVATARS.map((a, i) => (
                <span
                  key={a.letter}
                  className={cn(
                    'flex size-[26px] items-center justify-center rounded-full text-[11px] font-bold ring-2',
                    heroRing,
                    i > 0 && '-ml-1.5',
                    a.className,
                  )}
                >
                  {a.letter}
                </span>
              ))}
            </span>
            <span className="text-[13px] text-bk-muted sm:text-[15px]">One website each, a different look for every brand.</span>
          </div>

          <p
            className="mx-auto mt-[clamp(6px,1.4svh,24px)] max-w-[620px] text-[length:clamp(14px,2.1svh,17px)] leading-[1.45] text-bk-muted motion-safe:animate-bk-enter sm:text-[length:clamp(15px,2.1svh,19px)]"
            style={{ animationDelay: '140ms' }}
          >
            Batkle learns your brand from your website, then writes the ideas and designs the posts in your language,
            colors, fonts and logo.
          </p>

          <WebsiteForm />
        </div>

        {/* The illustration fills the remaining height; the cards rest on its lower edge. Below lg they swipe. */}
        <div className="relative mt-[clamp(8px,1.6svh,40px)] flex min-h-[clamp(120px,20svh,300px)] flex-1 flex-col justify-end">
          <HeroArt className="absolute inset-0 h-full w-full motion-safe:animate-bk-art" />
          <ul className="relative z-10 mx-4 flex snap-x snap-mandatory overflow-x-auto overflow-y-hidden rounded-t-[14px] bg-bk-surface [scrollbar-width:none] sm:mx-auto sm:w-full sm:max-w-[760px] lg:grid lg:max-w-[1000px] lg:grid-cols-3 lg:overflow-hidden [&::-webkit-scrollbar]:hidden">
            {HERO_CARDS.map((card, i) => (
              <li key={card.label} className={cn('w-[84%] shrink-0 snap-start sm:w-[48%] lg:w-auto', i > 0 && 'border-l border-bk-line')}>
                <a
                  href={card.href}
                  className="group flex h-full min-h-[clamp(88px,14svh,156px)] flex-col justify-between gap-[clamp(6px,1.2svh,12px)] p-[clamp(12px,1.9svh,20px)] transition-colors hover:bg-bk-alt/60 focus-visible:outline focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-bk-fg"
                >
                  <span className="flex items-center justify-between text-[13px] text-bk-fg/85">
                    {card.label}
                    <ArrowUpRight
                      className="size-3.5 transition-transform duration-200 group-hover:-translate-y-0.5 group-hover:translate-x-0.5"
                      aria-hidden="true"
                    />
                  </span>
                  <span className="flex items-end justify-between gap-4">
                    <span className="max-w-[9.5em] font-bk-display text-[length:clamp(16px,2.3svh,19px)] font-bold leading-[1.2] tracking-[-0.01em]">
                      {card.title}
                    </span>
                    <span aria-hidden="true">
                      <Thumb kind={card.thumb} />
                    </span>
                  </span>
                </a>
              </li>
            ))}
          </ul>
        </div>

        <div className="relative border-t border-bk-line bg-bk-surface">
          <div className="flex items-center gap-x-6 overflow-x-auto whitespace-nowrap px-4 py-[clamp(10px,1.8svh,20px)] text-[13px] [scrollbar-width:none] sm:mx-auto sm:max-w-[760px] sm:px-0 sm:text-[15px] lg:max-w-[1000px] lg:gap-x-8 [&::-webkit-scrollbar]:hidden">
            <span className="shrink-0 text-bk-muted">Built for teams in</span>
            <ul className="flex shrink-0 gap-x-6 font-bold lg:gap-x-8">
              {INDUSTRIES.map((name) => (
                <li key={name}>{name}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </section>
  )
}

function HowItWorks() {
  return (
    <Section id="how-it-works" tone="alt">
      <Eyebrow>How it works</Eyebrow>
      <SectionTitle className="max-w-[11em]">From a URL to a finished post in five steps.</SectionTitle>
      <ol {...reveal(2)} className="mt-12 border-t border-bk-fg sm:mt-14">
        {STEPS.map((step, i) => (
          <li
            key={step.title}
            className="grid gap-x-8 gap-y-2 border-b border-bk-field/70 py-7 sm:grid-cols-[56px_minmax(0,1fr)] md:grid-cols-[56px_minmax(0,1fr)_minmax(0,694px)] md:py-[30px]"
          >
            <p className="pt-1 text-[17px] font-bold text-bk-muted">{String(i + 1).padStart(2, '0')}</p>
            <h3 className="font-bk-display text-[24px] font-bold leading-tight tracking-[-0.03em] sm:text-[26px]">{step.title}</h3>
            <p className="text-[17px] leading-relaxed text-bk-muted sm:col-start-2 md:col-start-auto">{step.body}</p>
          </li>
        ))}
      </ol>
    </Section>
  )
}

function Demo() {
  return (
    <Section id="demo">
      <Eyebrow>Demo</Eyebrow>
      <SectionTitle>
        Every business gets its <br className="hidden sm:inline" />
        own look and its own voice.
      </SectionTitle>
      <p {...reveal(2)} className="mt-4 max-w-[720px] text-[17px] leading-relaxed text-bk-muted">
        Pick a type of business to see the brand profile Batkle builds and the post it drafts. Sample brands, for
        illustration.
      </p>
      <BrandDemo />
    </Section>
  )
}

const pill = 'inline-flex items-center rounded-full border border-bk-field px-3 py-1 text-[13px]'
const pillOn = 'inline-flex items-center rounded-full border border-transparent bg-bk-butter px-3 py-1 text-[13px] font-bold text-bk-ink'
const bodyText = 'mt-3 text-[17px] leading-[1.65] text-bk-muted'

function Features() {
  return (
    <Section id="features" tone="alt">
      <Eyebrow>Features</Eyebrow>
      <SectionTitle>
        Built around your brand, <br className="hidden sm:inline" />
        not around templates.
      </SectionTitle>

      <div className="mt-12 grid gap-5 sm:mt-14 lg:grid-cols-[minmax(0,1.59fr)_minmax(0,1fr)]">
        <Card i={2} lift className="flex flex-col gap-6 p-6 sm:flex-row sm:items-center sm:gap-9 sm:p-8">
          <div className="sm:w-[320px] sm:shrink-0">
            <CardTitle>It learns your brand from your website</CardTitle>
            <p className={bodyText}>
              No long setup. Batkle reads your site and builds the profile for you, grounded in your real services and
              projects.
            </p>
          </div>
          <ul className="flex max-w-[280px] flex-wrap gap-1.5" aria-label="What the brand profile covers">
            <li className={pillOn}>Services</li>
            <li className={pillOn}>Projects</li>
            {['Audience', 'Tone of voice', 'Language', 'Colors', 'Fonts', 'Logo'].map((item) => (
              <li key={item} className={pill}>
                {item}
              </li>
            ))}
          </ul>
        </Card>

        <Card i={3} lift className="p-6 sm:p-8">
          <CardTitle>Your language, your tone</CardTitle>
          <p className={bodyText}>Posts come out in your brand&apos;s language, European Portuguese included.</p>
          <ul className="mt-5 space-y-2 text-[15px]" aria-label="Example headlines">
            <li lang="pt-PT" className="rounded-lg border border-bk-line px-3 py-2.5">
              Casa limpa, cabeça leve.
            </li>
            <li className="rounded-lg border border-bk-line px-3 py-2.5">Pay every supplier in one click.</li>
          </ul>
        </Card>
      </div>

      <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1.59fr)_minmax(0,1fr)]">
        <Card i={0} lift className="flex flex-col gap-6 p-6 sm:flex-row sm:items-center sm:gap-9 sm:p-8">
          <div className="sm:w-[320px] sm:shrink-0">
            <CardTitle>Designs learned from real posts</CardTitle>
            <p className={bodyText}>
              Show the Design Library a few posts you like. It studies the layout, type and color roles, then applies
              that visual language to your brand.
            </p>
          </div>
          <div className="flex items-center gap-3" aria-hidden="true">
            <div className="flex flex-col gap-2">
              <span className="h-14 w-11 rounded-md border border-bk-field bg-[#EFEEE9] dark:bg-bk-chip" />
              <span className="h-14 w-11 rounded-md border border-bk-field bg-[#EFEEE9] dark:bg-bk-chip" />
            </div>
            <ArrowRight className="size-4 shrink-0" />
            <div className="flex h-[188px] w-[150px] items-end rounded-md bg-[#F2A900] p-2.5">
              <span className="font-bk-display text-[15px] font-bold leading-[1.1] tracking-[-0.02em] text-bk-ink">
                Your look, every post.
              </span>
            </div>
          </div>
        </Card>

        <Card i={1} lift className="p-6 sm:p-8">
          <CardTitle>Ideas that never repeat</CardTitle>
          <p className={bodyText}>Suggestions rotate across your services, projects and strengths.</p>
          <ul className="mt-5 space-y-2 text-[14px]" aria-label="Example ideas">
            {[
              ['Service', 'Why every project starts with a site visit'],
              ['Project', 'Before and after: a Lisbon rehab'],
              ['Strength', 'Meet the team behind the work'],
            ].map(([kind, idea]) => (
              <li key={kind} className="flex items-baseline gap-2">
                <span className="rounded-[5px] bg-bk-chip px-2 py-0.5 text-[12px] font-bold">{kind}</span>
                {idea}
              </li>
            ))}
          </ul>
        </Card>
      </div>

      <div className="mt-5 grid gap-5 md:grid-cols-3">
        <Card i={0} lift className="p-6 sm:p-8">
          <CardTitle>AI images and cutouts</CardTitle>
          <p className={bodyText}>AI-generated images and transparent cutouts, stock photos and your own gallery, all saved for reuse.</p>
          <div className="bk-checker mt-5 flex h-[85px] items-center justify-center rounded-lg border border-bk-line" aria-hidden="true">
            <span className="h-[60px] w-12 rounded-b-md rounded-t-full border-[1.5px] border-bk-ink bg-[#F2A900]" />
          </div>
        </Card>

        <Card i={1} lift className="p-6 sm:p-8">
          <CardTitle>Nothing is a flat image</CardTitle>
          <p className={bodyText}>Text, shapes, images and logo stay editable in the canvas editor. The AI drafts, you decide.</p>
          <ul className="mt-5 overflow-hidden rounded-lg border border-bk-line text-[14px]" aria-label="Example layers">
            <li className="bg-bk-butter px-3 py-2 font-bold text-bk-ink">Headline</li>
            <li className="border-t border-bk-line px-3 py-2">Image</li>
            <li className="border-t border-bk-line px-3 py-2">Logo</li>
          </ul>
        </Card>

        <Card i={2} lift className="p-6 sm:p-8">
          <CardTitle>Render through an API</CardTitle>
          <p className={bodyText}>Send dynamic data to a design and get the finished image back with a single API call.</p>
          <p className="mt-5 flex items-center gap-2.5 text-[13px] font-bold">
            <span className="rounded-md border border-bk-field px-2.5 py-1.5">Data</span>
            <ArrowRight className="size-3.5" aria-hidden="true" />
            <span className="rounded-md border border-bk-field px-2.5 py-1.5">Design</span>
            <ArrowRight className="size-3.5" aria-hidden="true" />
            <span className="rounded-md border border-transparent bg-bk-butter px-2.5 py-1.5 text-bk-ink">Image</span>
          </p>
        </Card>
      </div>
    </Section>
  )
}

function WhoItsFor() {
  return (
    <Section id="who-its-for">
      <Eyebrow>Who it&apos;s for</Eyebrow>
      <SectionTitle>
        For teams that post regularly but <br className="hidden md:inline" />
        don&apos;t want to design every post.
      </SectionTitle>
      <p {...reveal(2)} className="mt-4 text-[17px] leading-relaxed text-bk-muted">
        Construction firms, fintechs, local service companies, creative studios and everyone in between.
      </p>
      <div className="mt-12 grid gap-5 sm:mt-14 md:grid-cols-3">
        {AUDIENCES.map((a, i) => (
          <Card key={a.title} i={i + 3} lift className="p-6 sm:p-7">
            <CardTitle>{a.title}</CardTitle>
            <p className="mt-3 text-[17px] leading-relaxed text-bk-muted">{a.body}</p>
          </Card>
        ))}
      </div>
    </Section>
  )
}

function BeforeAfter() {
  return (
    <Section tone="alt">
      <SectionTitle>
        Your posting routine, <br className="hidden sm:inline" />
        before and after.
      </SectionTitle>
      <div className="mt-12 grid gap-5 sm:mt-14 md:grid-cols-2">
        <Card i={2} className="p-6 sm:p-9">
          <CardTitle className="text-[21px] text-bk-muted">Without Batkle</CardTitle>
          <ul className="mt-5 space-y-3.5">
            {WITHOUT.map((item) => (
              <li key={item} className="flex gap-3 text-[17px] text-bk-muted">
                <X className="mt-[3px] size-[18px] shrink-0" aria-hidden="true" />
                {item}
              </li>
            ))}
          </ul>
        </Card>
        <div {...reveal(3)} className="rounded-2xl border border-bk-fg bg-bk-surface p-6 shadow-bk-pop sm:p-9">
          <CardTitle className="text-[21px]">With Batkle</CardTitle>
          <ul className="mt-5 space-y-3.5">
            {WITH.map((item) => (
              <li key={item} className="flex gap-3 text-[17px]">
                <span className="mt-[2px] flex size-5 shrink-0 items-center justify-center rounded-full bg-bk-butter text-bk-ink">
                  <Check className="size-3" strokeWidth={3} aria-hidden="true" />
                </span>
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </Section>
  )
}

function Testimonials() {
  return (
    <Section>
      <SectionTitle>What customers say.</SectionTitle>
      <div className="mt-12 grid gap-5 sm:mt-14 md:grid-cols-2">
        {QUOTES.map((quote, i) => (
          <Card as="figure" key={quote} i={i + 2} className="p-6 sm:p-9">
            <blockquote className="font-bk-display text-[21px] font-bold leading-snug tracking-[-0.02em] sm:text-[24px]">
              {quote}
            </blockquote>
            <figcaption className="mt-6 flex items-center gap-3 text-[15px] text-bk-muted">
              <span aria-hidden="true" className="size-[42px] rounded-full border border-bk-field/70 bg-bk-alt" />
              [Name, role, company]
            </figcaption>
          </Card>
        ))}
      </div>
    </Section>
  )
}

function Pricing() {
  return (
    <Section id="pricing" tone="alt">
      <Eyebrow>Pricing</Eyebrow>
      <SectionTitle>Simple pricing, no surprises.</SectionTitle>
      <p {...reveal(2)} className="mt-4 text-[17px] uppercase text-bk-muted">[Add your real plans, prices and free trial details below]</p>
      <div className="mt-12 grid gap-5 sm:mt-14 md:grid-cols-3">
        {PLANS.map((plan, i) => (
          <div
            key={i}
            {...reveal(i + 2)}
            className={cn(
              'relative flex flex-col rounded-2xl border bg-bk-surface p-6 lg:p-8',
              plan.popular ? 'border-bk-fg shadow-bk-pop' : 'border-bk-line shadow-bk-card',
              liftClass,
            )}
          >
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h3 className="font-bk-display text-[19px] font-bold tracking-[-0.02em]">[PLAN NAME]</h3>
              {plan.popular && (
                <span className="rounded-full bg-bk-butter px-3 py-1 text-[12px] font-bold text-bk-ink md:absolute md:right-5 md:top-0 md:-translate-y-1/2 lg:static lg:translate-y-0">
                  Most popular
                </span>
              )}
            </div>
            <p className={cn(displayClass, 'mt-6 text-[40px] leading-none lg:text-[46px]')}>[PRICE]</p>
            <ul className="mt-6 space-y-3 text-[16px] text-bk-muted">
              <li>[FEATURE ONE]</li>
              <li>[FEATURE TWO]</li>
              <li>[FEATURE THREE]</li>
            </ul>
            <Link href={START_HREF} className={buttonClass(plan.popular ? 'primary' : 'outline', 'md', 'mt-7 w-full')}>
              Get started
            </Link>
          </div>
        ))}
      </div>
    </Section>
  )
}

function Faq() {
  return (
    <Section id="faq">
      <div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(0,740px)] lg:gap-16">
        <div>
          <Eyebrow>FAQ</Eyebrow>
          <SectionTitle className="max-w-[7.6em]">Frequently asked questions</SectionTitle>
        </div>
        <div {...reveal(2)} className="border-t border-bk-line">
          {FAQS.map((item) => (
            <details key={item.q} className="bk-faq group border-b border-bk-line">
              <summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-[22px] text-[17px] font-bold transition-colors can-hover:text-bk-fg/75 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-bk-fg sm:text-[18px] [&::-webkit-details-marker]:hidden">
                {item.q}
                <Plus className="size-5 shrink-0 transition-transform duration-300 group-open:rotate-45" aria-hidden="true" />
              </summary>
              <p className="bk-faq-answer -mt-1 max-w-[620px] pb-6 text-[17px] leading-relaxed text-bk-muted">{item.a}</p>
            </details>
          ))}
        </div>
      </div>
    </Section>
  )
}

function FinalCta() {
  return (
    <section className="bg-bk-bg pb-20 sm:pb-28 lg:pb-[120px]">
      <Container>
        <div {...reveal(0)} className="relative overflow-hidden rounded-[20px] bg-bk-ink px-6 pb-14 pt-32 sm:px-12 sm:py-20 lg:px-16 lg:py-[84px] dark:bg-bk-surface dark:ring-1 dark:ring-inset dark:ring-bk-line">
          <HangingBat
            className="absolute right-8 top-0 text-[44px] text-bk-butter sm:right-[10%] sm:text-[60px]"
            stemClassName="h-[44px] sm:h-[96px]"
          />
          <h2 className="font-bk-display text-[clamp(34px,4vw,54px)] font-bold leading-[1.05] tracking-[-0.02em] text-bk-cream">
            Paste your website. <br className="hidden sm:inline" />
            Get your first post.
          </h2>
          <p className="mt-6 max-w-[520px] text-[18px] leading-relaxed text-[#C4C1CE] sm:text-[19px]">
            Batkle learns your brand, drafts the ideas and designs the posts. You review, tweak and publish.
          </p>
          <Link href={START_HREF} className={buttonClass('primary', 'lg', 'mt-8')}>
            Add your brand <ArrowRight className={arrowClass} aria-hidden="true" />
          </Link>
        </div>
      </Container>
    </section>
  )
}

function Footer() {
  return (
    <footer className="border-t border-bk-line bg-bk-bg">
      <Container className="flex flex-col gap-12 py-14 sm:py-16 md:flex-row md:justify-between">
        <div>
          <BatkleLogo size={34} />
          <p className="mt-4 max-w-[300px] text-[15px] leading-relaxed text-bk-muted">
            On-brand Instagram posts and carousels, drafted by AI and finished by you.
          </p>
        </div>
        <div className="flex gap-16">
          {FOOTER_LINKS.map((group) => (
            <nav key={group.title} aria-label={group.title}>
              <p className="text-[13px] font-bold uppercase tracking-[0.12em] text-bk-muted">{group.title}</p>
              <ul className="mt-5 space-y-3.5">
                {group.links.map(([label, href]) => (
                  <li key={label}>
                    <Link href={href} className="text-[15px] text-bk-fg/90 transition-colors hover:text-bk-fg hover:underline hover:underline-offset-4">
                      {label}
                    </Link>
                  </li>
                ))}
              </ul>
            </nav>
          ))}
        </div>
      </Container>
      <div className="border-t border-bk-line">
        <Container className="py-6 text-[14px] text-bk-muted">© {new Date().getFullYear()} Batkle. All rights reserved.</Container>
      </div>
    </footer>
  )
}

export default function LandingPage({ className = '' }) {
  return (
    <div className={cn('bk-root min-h-screen bg-bk-bg font-bk-body text-bk-fg antialiased', className)}>
      <a
        href="#main"
        className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[60] focus:rounded-lg focus:bg-bk-butter focus:px-4 focus:py-2 focus:font-bold focus:text-bk-ink"
      >
        Skip to content
      </a>
      <ScrollReveal />
      <SmoothScroll />
      <CustomCursor />
      <LandingHeader />
      <main id="main">
        <Hero />
        <HowItWorks />
        <Demo />
        <Features />
        <WhoItsFor />
        <BeforeAfter />
        <Testimonials />
        <Pricing />
        <Faq />
        <FinalCta />
      </main>
      <Footer />
    </div>
  )
}
